---
- hosts: all
  gather_facts: true
  tasks:
   - name: install package for centos
     yum: name=git state=present
     when: ansible_distribution == "CentOS"
   - name: install pkg for ubuntu
     apt: name=git state=present
     when: ansible_distribution == "Ubuntu"
