---
filebeat_version: 6.x
filebeat_create_config: true
filebeat_output_logstash_enabled: true
filebeat_output_logstash_hosts:
  - "localhost:5044"

filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log

