---

- name: Ensure Logstash SSL key pair directory exists.
  file:
    path: "{{ logstash_ssl_dir }}"
    state: directory
  when: logstash_ssl_key_file

- name: Copy SSL key and cert for logstash-forwarder.
  copy:
    src: "{{ item }}"
    dest: "{{ logstash_ssl_dir }}/{{ item | basename }}"
    mode: 0644
  with_items:
    - "{{ logstash_ssl_key_file }}"
    - "{{ logstash_ssl_certificate_file }}"
  notify: restart logstash
  when: logstash_ssl_key_file

- name: Creates SSL directories
  file:
   path: /etc/pki/tls/certs
   state: directory

- name: Creates SSL directories
  file:
   path: /etc/pki/tls/private
   state: directory

- name: Generate SSL certificates
  shell: "openssl req -config /etc/ssl/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout /etc/pki/tls/private/logstash-forwarder.key -out /etc/pki/tls/certs/logstash-forwarder.crt"

- name: Configure Beats configuration file
  template:
   src=beats-input.conf.j2
   dest=/etc/logstash/conf.d/02-beats-input.conf
   owner=root
   group=root
   mode=0644

- name: Configure Elasticsearch output file
  template:
   src=elasticsearch-output.conf.j2
   dest=/etc/logstash/conf.d/30-elasticsearch-output.conf
   owner=root
   group=root
   mode=0644

- name: Start Logstash service
  systemd:
   name: logstash
   state: started
   daemon_reload: yes

- name: Enable Logstash service
  systemd:
   name: logstash
   enabled: yes
