---

# Elasticsearch defaults var
elasticsearch_major_version: 6.x
elasticsearch_cluster_name: my_cluster
elasticsearch_node_name: my_node
elasticsearch_network_host: localhost
elasticsearch_http_port: 9200
